repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: python mypy
        always_run: true
        pass_filenames: false
        args: ["."]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        name: ruff-check
        always_run: true
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        always_run: true
